CREATE TABLE payments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount             BIGINT                                  NOT NULL,
    currency_code      VARCHAR(255)                            NOT NULL,
    transaction_status VARCHAR(255)                            NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    idempotent_key     VARCHAR(255)                            NOT NULL,
    version            INTEGER,
    reason             VARCHAR(255),
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_idempotent_key UNIQUE (idempotent_key);